-- 0012_seed_demo_user.sql — DEPRECATED, no-op.
--
-- This migration originally inserted an `admin@demo.local` user
-- directly into auth.users + auth.identities so a fresh clone could
-- sign in without dashboard config. The seeded row caused "Database
-- error querying schema" on every sign-in attempt — most likely
-- because pgcrypto's gen_salt('bf') emits a `$2a$` bcrypt hash and
-- modern GoTrue strict-matches `$2b$`, but no row of diagnostic SQL
-- nailed it down.
--
-- The reliable path turned out to be Authentication → Users →
-- Add user in the Supabase dashboard, which calls
-- GoTrue's auth.admin.create_user() internally and fills every
-- column correctly.
--
-- Keeping the filename here so applied-migration tracking
-- (supabase_migrations.schema_migrations) doesn't drift. On a fresh
-- project this file is a no-op; seed the demo user via the dashboard
-- or via a post-migration script that calls the Supabase Management
-- API with the service-role key.

select 1 where false;
